import { Transaction } from './types/expense';
import { TaiwanInvoice } from './types/invoice';
import { Household } from './types/family';
import { UserProfile, LearningRule } from './types/user';

export const MOCK_USER: UserProfile = {
  uid: 'user_tw_01',
  email: 'chen.wei@example.com',
  displayName: '陳威廷',
  photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  defaultCarrierCode: '/AB1234+',
  defaultPaymentMethod: 'LINE Pay',
  activeHouseholdId: 'house_warm_family',
  monthlyBudget: 35000,
  preferences: {
    theme: 'system',
    currency: 'NT$',
    soundEnabled: true,
    hapticEnabled: true,
    autoDetectAnomaly: true,
  },
};

export const MOCK_USER_LIN: UserProfile = {
  uid: 'user_tw_02',
  email: 'yichun.lin@example.com',
  displayName: '林怡君 (老婆)',
  photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  defaultCarrierCode: '/XY9876-',
  defaultPaymentMethod: '全支付/PX Pay',
  activeHouseholdId: 'house_warm_family',
  monthlyBudget: 30000,
  preferences: {
    theme: 'light',
    currency: 'NT$',
    soundEnabled: true,
    hapticEnabled: true,
    autoDetectAnomaly: true,
  },
};

export const MOCK_HOUSEHOLD: Household = {
  id: 'house_warm_family',
  name: '幸福溫馨小窩 🏡',
  inviteCode: 'TW8888',
  ownerId: 'user_tw_01',
  members: [
    {
      userId: 'user_tw_01',
      displayName: '陳威廷 (我)',
      email: 'chen.wei@example.com',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'owner',
      carrierCode: '/AB1234+',
      joinedAt: Date.now() - 30 * 86400000,
    },
    {
      userId: 'user_tw_02',
      displayName: '林怡君 (老婆)',
      email: 'yichun.lin@example.com',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      role: 'admin',
      carrierCode: '/XY9876-',
      joinedAt: Date.now() - 25 * 86400000,
    },
  ],
  currency: 'NT$',
  defaultSplitMethod: 'equal',
  monthlyBudget: 45000,
  createdAt: Date.now() - 30 * 86400000,
  updatedAt: Date.now(),
};

const today = new Date().toISOString().split('T')[0];

export const MOCK_TRANSACTIONS: Transaction[] = [
  // --- 家庭公用開銷 (雙方共用，但記錄是誰代墊) ---
  {
    id: 'tx_01',
    userId: 'user_tw_01',
    householdId: 'house_warm_family',
    title: '全聯生活生鮮採買 (週末煮火鍋)',
    amount: 1280,
    type: 'expense',
    ledgerType: 'household',
    categoryId: 'housing',
    categoryName: '居家生活',
    categoryIcon: 'Home',
    subCategory: '日用品消耗',
    paymentMethod: '全支付/PX Pay',
    date: today,
    merchant: '全聯實業',
    note: '買了牛肉片、高麗菜、火鍋底料與抽取式衛生紙',
    tags: ['家庭公用', '生活採買', '生鮮食材'],
    invoiceNumber: 'AB-32117043',
    splitInfo: {
      splitMethod: 'equal',
      payerId: 'user_tw_01',
      splits: [
        { userId: 'user_tw_01', amount: 640, settled: false },
        { userId: 'user_tw_02', amount: 640, settled: false },
      ],
    },
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: 'tx_03',
    userId: 'user_tw_02',
    householdId: 'house_warm_family',
    title: '台電電費 (7-8月夏季用電)',
    amount: 2450,
    type: 'expense',
    ledgerType: 'household',
    categoryId: 'housing',
    categoryName: '居家生活',
    categoryIcon: 'Home',
    subCategory: '水電瓦斯',
    paymentMethod: '銀行轉帳',
    date: today,
    merchant: '台灣電力公司',
    note: '夏季冷氣電費',
    tags: ['家庭公用', '固定繳費'],
    splitInfo: {
      splitMethod: 'equal',
      payerId: 'user_tw_02',
      splits: [
        { userId: 'user_tw_01', amount: 1225, settled: false },
        { userId: 'user_tw_02', amount: 1225, settled: false },
      ],
    },
    createdAt: Date.now() - 28800000,
    updatedAt: Date.now() - 28800000,
  },

  // --- 陳威廷 (user_tw_01) 專屬個人私帳 ---
  {
    id: 'tx_02',
    userId: 'user_tw_01',
    title: '一蘭拉麵 + 抹茶杏仁豆腐',
    amount: 380,
    type: 'expense',
    ledgerType: 'personal',
    categoryId: 'food',
    categoryName: '餐飲飲食',
    categoryIcon: 'Utensils',
    subCategory: '午餐',
    paymentMethod: '街口支付',
    date: today,
    merchant: '一蘭拉麵',
    note: '跟同事一起吃中午',
    tags: ['外食', '同事聚餐'],
    invoiceNumber: 'CD-88392019',
    createdAt: Date.now() - 14400000,
    updatedAt: Date.now() - 14400000,
  },
  {
    id: 'tx_04',
    userId: 'user_tw_01',
    title: '星巴克 特選馥列白大杯',
    amount: 150,
    type: 'expense',
    ledgerType: 'personal',
    categoryId: 'food',
    categoryName: '餐飲飲食',
    categoryIcon: 'Utensils',
    subCategory: '咖啡外帶',
    paymentMethod: 'LINE Pay',
    date: today,
    merchant: '星巴克',
    note: '上班前提神',
    tags: ['咖啡', '工作提神'],
    createdAt: Date.now() - 32400000,
    updatedAt: Date.now() - 32400000,
  },
  {
    id: 'tx_05',
    userId: 'user_tw_01',
    title: '台灣中油 95無鉛汽油加滿',
    amount: 1150,
    type: 'expense',
    ledgerType: 'personal',
    categoryId: 'transport',
    categoryName: '交通運輸',
    categoryIcon: 'Car',
    subCategory: '加油費',
    paymentMethod: '信用卡 (一般)',
    date: today,
    merchant: '台灣中油',
    tags: ['加油', '交通'],
    invoiceNumber: 'EF-99281740',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: 'tx_06',
    userId: 'user_tw_01',
    title: '8月份 正職工程師薪資發放',
    amount: 72000,
    type: 'income',
    ledgerType: 'personal',
    categoryId: 'income_salary',
    categoryName: '薪資收入',
    categoryIcon: 'Briefcase',
    subCategory: '正職月薪',
    paymentMethod: '銀行轉帳',
    date: today,
    note: '8月公司薪水入帳',
    tags: ['薪資', '固定收入'],
    createdAt: Date.now() - 172800000,
    updatedAt: Date.now() - 172800000,
  },

  // --- 林怡君 (user_tw_02) 專屬個人私帳 ---
  {
    id: 'tx_lin_01',
    userId: 'user_tw_02',
    title: '寶雅生活館 醫美玻尿酸精華液 & 面膜',
    amount: 890,
    type: 'expense',
    ledgerType: 'personal',
    categoryId: 'shopping',
    categoryName: '日常購物',
    categoryIcon: 'ShoppingBag',
    subCategory: '美妝保養',
    paymentMethod: 'LINE Pay',
    date: today,
    merchant: '寶雅 POYA',
    note: '補貨日常保養品',
    tags: ['美妝保養', '個人護理'],
    invoiceNumber: 'XY-55201928',
    createdAt: Date.now() - 18000000,
    updatedAt: Date.now() - 18000000,
  },
  {
    id: 'tx_lin_02',
    userId: 'user_tw_02',
    title: 'Lady M 伯爵千層蛋糕 & 皇家伯爵茶',
    amount: 320,
    type: 'expense',
    ledgerType: 'personal',
    categoryId: 'food',
    categoryName: '餐飲飲食',
    categoryIcon: 'Utensils',
    subCategory: '甜點下午茶',
    paymentMethod: '信用卡 (一般)',
    date: today,
    merchant: 'Lady M 旗艦店',
    note: '跟閨蜜吃下午茶',
    tags: ['下午茶', '甜點', '個人放鬆'],
    createdAt: Date.now() - 10800000,
    updatedAt: Date.now() - 10800000,
  },
  {
    id: 'tx_lin_03',
    userId: 'user_tw_02',
    title: '8月份 UI/UX 設計主管薪資發放',
    amount: 65000,
    type: 'income',
    ledgerType: 'personal',
    categoryId: 'income_salary',
    categoryName: '薪資收入',
    categoryIcon: 'Briefcase',
    subCategory: '正職月薪',
    paymentMethod: '銀行轉帳',
    date: today,
    note: '8月設計主管薪水入帳',
    tags: ['薪資', '固定收入'],
    createdAt: Date.now() - 172800000,
    updatedAt: Date.now() - 172800000,
  },
];

export const MOCK_INVOICES: TaiwanInvoice[] = [
  // 陳威廷 (/AB1234+) 的發票
  {
    id: 'inv_mock_01',
    invoiceNumber: 'AB-32117043',
    date: today,
    rocDate: '1130816',
    randomCode: '6812',
    salesAmount: 1219,
    totalAmount: 1280,
    buyerGUI: '00000000',
    sellerGUI: '16740494',
    sellerName: '全聯實業股份有限公司',
    carrierCode: '/AB1234+',
    isScanned: true,
    scanTime: Date.now() - 3600000,
    items: [
      { name: '冷藏美國牛五花火鍋肉片', quantity: 2, unitPrice: 280, amount: 560 },
      { name: '產銷履歷高麗菜', quantity: 1, unitPrice: 85, amount: 85 },
      { name: '海底撈麻辣火鍋底料', quantity: 1, unitPrice: 195, amount: 195 },
      { name: '舒潔抽取式衛生紙 100抽*8包', quantity: 2, unitPrice: 220, amount: 440 },
    ],
    lotteryResult: {
      isWon: true,
      prizeName: '頭獎',
      prizeAmount: 200000,
      matchedNumber: '32117043',
      detail: '恭喜！發票號碼 32117043 與 113年07-08月頭獎完全相符，獲得 20 萬元！',
    },
  },
  {
    id: 'inv_mock_02',
    invoiceNumber: 'CD-88392019',
    date: today,
    rocDate: '1130816',
    randomCode: '4421',
    salesAmount: 362,
    totalAmount: 380,
    buyerGUI: '00000000',
    sellerGUI: '22555003',
    sellerName: '統一超商 7-ELEVEN',
    carrierCode: '/AB1234+',
    isScanned: true,
    scanTime: Date.now() - 14400000,
    items: [
      { name: '日式豚骨拉麵特盛', quantity: 1, unitPrice: 299, amount: 299 },
      { name: '抹茶杏仁豆腐', quantity: 1, unitPrice: 81, amount: 81 },
    ],
    lotteryResult: {
      isWon: false,
      prizeName: '未中獎',
      prizeAmount: 0,
    },
  },
  {
    id: 'inv_mock_03',
    invoiceNumber: 'EF-99281740',
    date: today,
    rocDate: '1130815',
    randomCode: '9120',
    salesAmount: 1095,
    totalAmount: 1150,
    buyerGUI: '00000000',
    sellerGUI: '28086000',
    sellerName: '台灣中油股份有限公司',
    carrierCode: '/AB1234+',
    isScanned: true,
    scanTime: Date.now() - 86400000,
    items: [{ name: '95無鉛汽油 35.8公升', quantity: 1, unitPrice: 1150, amount: 1150 }],
    lotteryResult: {
      isWon: false,
      prizeName: '未中獎',
      prizeAmount: 0,
    },
  },

  // 林怡君 (/XY9876-) 的發票
  {
    id: 'inv_mock_lin_01',
    invoiceNumber: 'XY-55201928',
    date: today,
    rocDate: '1130816',
    randomCode: '1398',
    salesAmount: 848,
    totalAmount: 890,
    buyerGUI: '00000000',
    sellerGUI: '23859200',
    sellerName: '寶雅國際股份有限公司',
    carrierCode: '/XY9876-',
    isScanned: true,
    scanTime: Date.now() - 18000000,
    items: [
      { name: '玻尿酸保濕精華液 50ml', quantity: 1, unitPrice: 650, amount: 650 },
      { name: '茶樹控油面膜 5入裝', quantity: 1, unitPrice: 240, amount: 240 },
    ],
    lotteryResult: {
      isWon: true,
      prizeName: '六獎',
      prizeAmount: 200,
      matchedNumber: '55201928',
      detail: '恭喜！發票末三碼 928 對中 113年07-08月增開六獎，獲得 200 元！',
    },
  },
];

export const MOCK_LEARNING_RULES: LearningRule[] = [
  {
    id: 'rule_01',
    userId: 'user_tw_01',
    householdId: 'house_warm_family',
    vendorPattern: '星巴克',
    keywordPattern: '咖啡',
    targetCategoryId: 'food',
    targetCategoryName: '餐飲飲食',
    targetSubCategory: '咖啡外帶',
    targetTags: ['咖啡', '工作提神'],
    targetPaymentMethod: 'LINE Pay',
    confidence: 0.95,
    usageCount: 12,
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 100000,
  },
  {
    id: 'rule_02',
    userId: 'user_tw_01',
    householdId: 'house_warm_family',
    vendorPattern: '全聯',
    keywordPattern: '買菜',
    targetCategoryId: 'housing',
    targetCategoryName: '居家生活',
    targetSubCategory: '日用品消耗',
    targetTags: ['家庭公用', '生活採買'],
    targetPaymentMethod: '全支付/PX Pay',
    confidence: 0.98,
    usageCount: 20,
    createdAt: Date.now() - 2000000,
    updatedAt: Date.now() - 200000,
  },
];
